'use client';

import { motion } from 'framer-motion';
import { useMemo } from 'react';
import { THEME } from '@/lib/theme';
import type { Finding } from '@/lib/risk-engine';
import type { assembleDocument } from '@/lib/document-engine';

type Doc = ReturnType<typeof assembleDocument>;

/**
 * Instant document preview.
 *
 * Renders the assembled clause tree on a light "paper" surface -- deliberately
 * inverted from the app chrome, because a legal draft the client will print or
 * sign should look like the document, not like the tool.
 *
 * Clauses carrying a risk finding get a gold margin marker. Matching is by
 * clause heading, which is why `document-engine` and `risk-engine` must keep
 * their `clause` strings in step.
 */
export function DocumentPreview({
  doc,
  findings,
}: {
  doc: Doc;
  findings: readonly Finding[];
}) {
  // Heading -> worst severity, so the margin marker reflects the top issue.
  const flagged = useMemo(() => {
    const rank = { info: 0, low: 1, medium: 2, high: 3, critical: 4 } as const;
    const map = new Map<string, Finding>();
    for (const f of findings) {
      const existing = map.get(f.clause);
      if (!existing || rank[f.severity] > rank[existing.severity]) {
        map.set(f.clause, f);
      }
    }
    return map;
  }, [findings]);

  return (
    <div>
      <div className="flex items-center justify-between border-b border-ink-500/15 px-5 py-3">
        <p className="eyebrow">Live draft</p>
        <p className="font-mono text-[11px] text-ink-500">
          {doc.clauses.length} clauses
        </p>
      </div>

      <div className="max-h-[520px] overflow-y-auto bg-[#F6F3EA] px-6 py-7 text-[#1A1A1A] sm:px-8">
        <header className="mb-6 text-center">
          <p className="text-[10px] uppercase tracking-[0.3em] text-[#8A6F1F]">
            Lex Maris
          </p>
          <h3 className="mt-2 font-display text-lg uppercase tracking-[0.06em]">
            {doc.title}
          </h3>
          <div className="mx-auto mt-3 h-px w-16 bg-[#8A6F1F]/50" />
        </header>

        <div className="space-y-2 text-[12.5px] leading-relaxed">
          {doc.recitals.map((r) => (
            <p key={r}>{r}</p>
          ))}
        </div>

        <ol className="mt-7 space-y-5">
          {doc.clauses.map((c) => {
            const finding = flagged.get(c.heading);
            const color = finding
              ? finding.severity === 'critical'
                ? THEME.status.critical
                : finding.severity === 'high'
                  ? THEME.status.risk
                  : THEME.gold700
              : undefined;

            return (
              <motion.li
                key={c.id}
                id={`clause-${c.id}`}
                layout
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.3 }}
                className="relative pl-4"
                style={
                  color
                    ? { borderLeft: `2px solid ${color}`, marginLeft: '-2px' }
                    : { borderLeft: '2px solid transparent' }
                }
              >
                <h4 className="text-[12.5px] font-semibold uppercase tracking-[0.05em]">
                  {c.number}. {c.heading}
                </h4>
                {finding && (
                  <p
                    className="mt-1 text-[10.5px] font-medium uppercase tracking-[0.1em]"
                    style={{ color }}
                  >
                    {finding.severity} — {finding.title}
                  </p>
                )}
                <div className="mt-1.5 space-y-2 text-[12.5px] leading-relaxed text-[#2A2A2A]">
                  {c.body.map((p, i) => (
                    <p key={i}>
                      <span className="mr-1.5 text-[#8A6F1F]">
                        {c.number}.{i + 1}
                      </span>
                      {p}
                    </p>
                  ))}
                </div>
              </motion.li>
            );
          })}
        </ol>

        <footer className="mt-8 border-t border-[#1A1A1A]/15 pt-4 text-[10px] uppercase tracking-[0.14em] text-[#6A6A6A]">
          Draft — not for execution. Generated by the Lex Maris document engine.
        </footer>
      </div>
    </div>
  );
}
